<?php

/**
 * @file
 * Advertising Entity: AdTech Factory module file.
 */

/**
 * Implements hook_library_info_build().
 */
function ad_entity_adtech_library_info_build() {
  $libraries = [];

  if ($config = \Drupal::service('config.factory')->get('ad_entity.settings')) {
    $settings = $config->get('adtech_factory');
    if (!empty($settings['library_source'])) {
      $libraries['provider'] = [
        'version' => '1.x',
        'header' => TRUE,
        'js' => [
          $settings['library_source'] => ['type' => 'external'],
        ],
      ];
    }
  }

  return $libraries;
}

/**
 * Implements template_preprocess_page().
 */
function ad_entity_adtech_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'ad_entity_adtech/provider';
}
