<?php

/**
 * @file
 * Advertising Entity install file.
 */

/**
 * Enable new settings for the behavior on context data reset.
 */
function ad_entity_update_8001() {
  if ($config = \Drupal::configFactory()->getEditable('ad_entity.settings')) {
    $behavior_reset = [
      'include_entity_info' => TRUE,
      'collect_default_data' => TRUE,
    ];
    $config->set('behavior_on_context_reset', $behavior_reset);
    $config->save();
  }
}
