ad_entity.settings:
  type: config_object
  label: 'Global settings for Advertising entities'

ad_entity.ad_entity.*:
  type: config_entity
  label: 'Advertising entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
