ad_entity.settings:
  type: config_object
  label: 'Global settings for Advertising entities'
  mapping:
    enable_responsive_behavior:
      type: boolean
      label: 'Whether responsive behavior is enabled or not'
    behavior_on_context_reset:
      type: mapping
      label: 'Behavior when backend context has been reset to the scope of an entity'
      mapping:
        include_entity_info:
          type: boolean
          label: 'Include elementary targeting information about the entity scope (type, label, uuid)'
        collect_default_data:
          type: boolean
          label: 'Enforce the collection of default Advertising context from the entity scope'

ad_entity.ad_entity.*:
  type: config_entity
  label: 'Advertising entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    type_plugin_id:
      type: string
      label: 'Type plugin id'
    view_plugin_id:
      type: string
      label: 'View handler plugin id'
    disable_initialization:
      type: boolean
      label: 'Disable automatic initialization'

ad_entity.display.*:
  type: config_entity
  label: 'Display config for Advertisement'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    variants:
      type: sequence
      label: 'List of variants to display, keyed by themes.'
      sequence:
        type: sequence
        label: 'List of variants for a theme, keyed by Advertising entities.'
        sequence:
          type: string
          label: 'JSON-encoded string of breakpoints, where the given Advertising entity should be displayed.'
    fallback:
      type: mapping
      label: 'Fallback settings'
      mapping:
        use_base_theme:
          type: boolean
          label: 'Use the display settings of a base theme, if available.'
        use_settings_from:
          type: string
          label: 'Use display settings of theme'

field.formatter.settings.ad_entity_context:
  type: mapping
  label: 'Advertising entity context formatter settings'
  mapping:
    appliance_mode:
      type: string
      label: 'Appliance mode'
    targeting:
      type: mapping
      label: 'Targeting'
      mapping:
        bundle_label:
          type: boolean
          label: 'Include "bundle: label" information'

field.formatter.settings.node_with_terms_context:
  type: field.formatter.settings.ad_entity_context
  label: 'Context from node with terms formatter settings'

field.formatter.settings.node_with_tree_aggregation_context:
  type: field.formatter.settings.ad_entity_context
  label: 'Context from node with tree aggregation formatter settings'

field.formatter.settings.node_with_tree_override_context:
  type: field.formatter.settings.ad_entity_context
  label: 'Context form node with tree override formatter settings'

field.formatter.settings.tree_aggregation_context:
  type: field.formatter.settings.ad_entity_context
  label: 'Context from taxonomy tree aggregation formatter settings'

field.formatter.settings.tree_override_context:
  type: field.formatter.settings.ad_entity_context
  label: 'Context from taxonmoy tree override formatter settings'
