<?php

/**
 * @file
 * Advertising Entity: DFP module file.
 */

/**
 * Implements template_preprocess_page().
 */
function ad_entity_dfp_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'ad_entity_dfp/provider';
}

/**
 * Implements hook_theme().
 */
function ad_entity_dfp_theme($existing, $type, $theme, $path) {
  return [
    'dfp_default' => [
      'variables' => ['ad_entity' => NULL],
      'file' => 'ad_entity_dfp.theme.inc',
    ],
    'dfp_iframe' => [
      'variables' => ['ad_entity' => NULL],
      'file' => 'ad_entity_dfp.iframe.inc',
    ],
    'dfp_amp' => [
      'variables' => ['ad_entity' => NULL],
      'file' => 'ad_entity_dfp.amp.inc',
    ],
  ];
}
