<?php

/**
 * @file
 * Advertising Entity: DFP module file.
 */

/**
 * Implements hook_ad_entity_module_info().
 */
function ad_entity_dfp_ad_entity_module_info() {
  return [
    'personalization' => TRUE,
    'consent_aware' => TRUE,
  ];
}

/**
 * Implements hook_page_attachments().
 */
function ad_entity_dfp_page_attachments(&$attachments) {
  $attachments['#attached']['library'][] = 'ad_entity_dfp/provider';
}

/**
 * Implements hook_theme().
 */
function ad_entity_dfp_theme($existing, $type, $theme, $path) {
  return [
    'dfp_default' => [
      'variables' => ['ad_entity' => NULL],
      'file' => 'ad_entity_dfp.theme.inc',
    ],
    'dfp_iframe' => [
      'variables' => ['ad_entity' => NULL],
      'file' => 'ad_entity_dfp.iframe.inc',
    ],
    'dfp_amp' => [
      'variables' => ['ad_entity' => NULL],
      'file' => 'ad_entity_dfp.amp.inc',
    ],
  ];
}
