ad_entity.ad_entity.*.third_party_settings.ad_entity_dfp:
  type: mapping
  label: 'Entity config for the DFP type'
  mapping:
    network_id:
      type: string
      label: 'DFP Network ID'
    unit_id:
      type: string
      label: 'DFP Ad Unit ID / Pattern'
    sizes:
      type: string
      label: 'Ad size formats'
    targeting:
      type: string
      label: 'Default pairs of key-values for targeting on the ad tag'
