ad_entity.settings.dfp:
  type: mapping
  label: 'Global settings for the DFP type.'
  mapping:
    order_info:
      type: boolean
      label: 'Include targeting information about the slot loading order'
    change_correlator:
      type: boolean
      label: 'Whether or not a new correlator is to be generated for fetching ads.'

ad_entity.ad_entity.*.third_party_settings.ad_entity_dfp:
  type: mapping
  label: 'Entity config for DFP ads'
  mapping:
    network_id:
      type: string
      label: 'DFP Network ID'
    unit_id:
      type: string
      label: 'DFP Ad Unit ID / Pattern'
    sizes:
      type: string
      label: 'Ad size formats'
    out_of_page:
      type: boolean
      label: 'Define as out of page slot'
    targeting:
      type: ignore
      label: 'Default pairs of key-values for targeting on the ad tag'
    iframe:
      type: mapping
      label: 'iFrame view settings'
      mapping:
        width:
          type: string
          label: 'iFrame width'
        height:
          type: string
          label: 'iFrame height'
    amp:
      type: mapping
      label: 'AMP tag view settings'
      mapping:
        width:
          type: string
          label: 'AMP-AD tag width'
        height:
          type: string
          label: 'AMP-AD tag height'
        multi_size_validation:
          type: boolean
          label: 'Enable multi-size validation'
        same_domain_rendering:
          type: boolean
          label: 'Enable same domain rendering'
        consent:
          label: 'Personalization by consent'
          type: mapping
          mapping:
            block_behavior:
              type: string
              label: 'Blocking behavior'
            npa_unknown:
              type: boolean
              label: 'Request non-personalized ads when consent is unknown.'
        rtc_config:
          type: mapping
          label: 'RTC Config'
          mapping:
            vendors:
              type: mapping
              label: 'Vendors'
              mapping:
                num_vendors:
                  type: integer
                  label: 'Number of Vendors'
                timeoutMillis:
                  type: integer
                  label: 'Timeout milliseconds'
                urls:
                  type: string
                  label: 'Urls'
                vendor_items:
                  type: sequence
                  label: 'Vendor Items'
                  sequence:
                    type: mapping
                    label: 'Vendor Item'
                    mapping:
                      vendor:
                        type: string
                        label: 'Vendor name'
                      vendor_values:
                        type: string
                        label: 'Vendor values'
